logstash:
  image: elastic/logstash:6.2.3
  volumes:
    - .:/app
  command: logstash -f /app/logstash.config
  links:
    - elasticsearch
  ports:
    - 5044:5044
elasticsearch:
  image: elastic/elasticsearch:6.2.3
  ports:
    - 9200:9200
    - 9300:9300
kibana:
  image: elastic/kibana:6.2.3
  links:
    - elasticsearch
  ports:
    - 5601:5601
