logstash:
  image: docker.elastic.co/logstash/logstash:6.2.3
  volumes:
    - .:/app
  command: logstash -f /app/logstash.config
  links:
    - elasticsearch
  ports:
    - 5044:5044
elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
  ports:
    - 9200:9200
    - 9300:9300
kibana:
  image: docker.elastic.co/kibana/kibana:6.2.3
  links:
    - elasticsearch
  ports:
    - 5601:5601
